[workspace]
members = ["crates/*"]

[workspace.package]
authors = ["Toby Fleming <tobywf@users.noreply.github.com>"]
# categories
# description
# documentation
edition = "2021"
# exclude
# homepage
# include
# keywords
# license
# license-file
publish = false
# readme
# repository
# rust-version
version = "0.0.0"

[profile.dev]
opt-level = 1
panic = "unwind"

[profile.release]
opt-level = 3
panic = "unwind"
lto = true
# the Windows build breaks when this is enabled
# codegen-units = 1
