[package]
name = "mech3ax-types-proc-macro"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

autoexamples = false
autobenches = false

[lib]
proc-macro = true
doctest = false

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
