[package]
name = "mech3ax-encoding"
version = "0.0.0"
authors = ["Toby Fleming <tobywf@users.noreply.github.com>"]
edition = "2021"
publish = false

autoexamples = false
autobenches = false
build = "build.rs"

[lib]
doctest = false
