[package]
name = "mech3ax-common"
version = "0.0.0"
authors = ["Toby Fleming <tobywf@users.noreply.github.com>"]
edition = "2021"
publish = false

autoexamples = false
autobenches = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
base64 = "0.13"
bitflags = "1.0"
num-traits = "0.2"

pelite = "0.9.0"
image = { version = "0.23", default-features = false }
thiserror = "1.0"

[dev-dependencies]
matches = "0.1.8"

[lib]
doctest = false
