[package]
name = "mech3ax-crc32"
version = "0.0.0"
authors = ["Toby Fleming <tobywf@users.noreply.github.com>"]
edition = "2021"
publish = false
build = "build.rs"

autoexamples = false
autobenches = false

[lib]
doctest = false
test = false
