[package]
name = "mech3ax-version"
version = "0.0.0"
authors = ["Toby Fleming <tobywf@users.noreply.github.com>"]
edition = "2021"
publish = false

autoexamples = false
autobenches = false

[dependencies]

[build-dependencies]
time = "0.3.5"

[lib]
doctest = false
test = false
