[package]
name = "mech3ax-timestamp"
authors.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true

autoexamples = false
autobenches = false

[dependencies]
time = { workspace = true, features = ["formatting", "parsing"] }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
serde_test.workspace = true
