[package]
name = "rezbd"
version = "0.0.0"
authors = ["Toby Fleming <tobywf@users.noreply.github.com>"]
edition = "2021"
publish = false

autoexamples = false
autobenches = false

[dependencies]
anyhow = "1.0"
clap = { version = "3.0.0", default-features = false, features = ["std", "derive", "color"] }
env_logger = { version = "0.9", default-features = false, features = ["atty", "humantime"] }
image = { version = "0.23", default-features = false, features = ["png"] }
serde = "1.0"
serde_json = "1.0"
zip = { version = "0.5", default-features = false, features = ["deflate"] }

mech3ax-anim = { path = "../mech3ax-anim" }
mech3ax-api-types = { path = "../mech3ax-api-types" }
mech3ax-archive = { path = "../mech3ax-archive" }
mech3ax-common = { path = "../mech3ax-common" }
mech3ax-gamez = { path = "../mech3ax-gamez" }
mech3ax-image = { path = "../mech3ax-image" }
mech3ax-interp = { path = "../mech3ax-interp" }
mech3ax-motion = { path = "../mech3ax-motion" }
mech3ax-reader = { path = "../mech3ax-reader" }
mech3ax-saves = { path = "../mech3ax-saves" }
mech3ax-version = { path = "../mech3ax-version" }
