[package]
name = "rezbd"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

autoexamples = false
autobenches = false

[dependencies]
clap.workspace = true
color-eyre.workspace = true
env_logger.workspace = true
eyre.workspace = true
image.workspace = true
log.workspace = true
serde_json.workspace = true
serde.workspace = true
zip.workspace = true

mech3ax-anim = { path = "../anim" }
mech3ax-api-types = { path = "../api-types" }
mech3ax-archive = { path = "../archive" }
mech3ax-common = { path = "../common" }
mech3ax-gamez = { path = "../gamez" }
mech3ax-image = { path = "../image" }
mech3ax-interp = { path = "../interp" }
mech3ax-motion = { path = "../motion" }
mech3ax-reader = { path = "../reader" }
mech3ax-saves = { path = "../saves" }
mech3ax-version = { path = "../version" }
mech3ax-zmap = { path = "../zmap" }
