[package]
name = "mech3ax-encoding"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

build = "build.rs"

autoexamples = false
autobenches = false

[lib]
doctest = false
test = true
