[package]
name = "mech3ax-metadata-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
doctest = false

[dependencies]
time = { version = "0.3.5" }
